export const i18nNotes = {
  es: {
    title: 'Mis Notas',
    noNotesYet: 'No tienes notas aún',
    viewAllNotes: 'Ver todas tus notas guardadas aquí.',
    goToNotesPage: 'Ir a la página de notas',
    untitled: 'Sin título',
    delete: 'Eliminar',
    edit: 'Editar',
    captureText: 'Capturar texto',
    closeNotes: 'Cerrar notas',
    openNotes: 'Abrir notas',
    notes: 'Notas',
    newNote: 'Nueva nota',
    editNote: 'Editar Nota',
    moveWindow: 'Mover ventana de notas',
    dragToMove: 'Arrastra para mover',
    closeWindow: 'Cerrar ventana de notas',
    selectedText: 'Texto seleccionado:',
    annotation: 'Anotación:',
    noteTitlePlaceholder: 'Título de la nota...',
    noteContentPlaceholder: 'Escribe tu nota aquí...',
    cancel: 'Cancelar',
    save: 'Guardar',
    textSizeLabel: 'Tamaño de texto',
    paragraph: 'Párrafo',
    heading1: 'Título 1',
    heading2: 'Título 2',
    heading3: 'Título 3',
    bold: 'Negrita',
    italic: 'Cursiva',
    underline: 'Subrayado',
    alignLeft: 'Alinear a la izquierda',
    alignLeftTitle: 'Izquierda',
    alignCenter: 'Centrar',
    alignRight: 'Alinear a la derecha',
    alignRightTitle: 'Derecha',
    alignJustify: 'Justificar',
    bulletList: 'Lista con viñetas',
    bulletListTitle: 'Lista',
    orderedList: 'Lista numerada',
    orderedListTitle: 'Numerada',
    blockquote: 'Cita',
    horizontalRule: 'Línea horizontal',
    horizontalRuleTitle: 'Línea',
    undo: 'Deshacer',
    redo: 'Rehacer',
    noNotes: 'No tienes notas guardadas',
    noteCount: (n: number) => `${n} ${n === 1 ? 'nota guardada' : 'notas guardadas'}`,
    colSection: 'Sección',
    colLastUpdate: 'Última actualización',
    colCount: 'Cantidad',
    colActions: 'Acciones',
    collapse: 'Contraer',
    expand: 'Expandir',
    collapseLabel: 'CONTRAER',
    expandLabel: 'EXPANDIR',
    downloadTXT: 'Descargar TXT',
    preparingPDF: 'Preparando PDF...',
    exportPDF: 'Exportar PDF',
    emptyText: 'Aún no has creado ninguna nota',
    emptyHint: 'Selecciona texto en cualquier página y haz clic en el ícono de notas para comenzar',
    noContent: 'Sin contenido',
    allPages: 'Todas las páginas',
    cover: 'Portada',
    page: (n: string) => `Página ${n}`
  },
  en: {
    title: 'My Notes',
    noNotesYet: 'You have no notes yet',
    viewAllNotes: 'View all your saved notes here.',
    goToNotesPage: 'Go to the notes page',
    untitled: 'Untitled',
    delete: 'Delete',
    edit: 'Edit',
    captureText: 'Capture text',
    closeNotes: 'Close notes',
    openNotes: 'Open notes',
    notes: 'Notes',
    newNote: 'New note',
    editNote: 'Edit Note',
    moveWindow: 'Move notes window',
    dragToMove: 'Drag to move',
    closeWindow: 'Close notes window',
    selectedText: 'Selected text:',
    annotation: 'Annotation:',
    noteTitlePlaceholder: 'Note title...',
    noteContentPlaceholder: 'Write your note here...',
    cancel: 'Cancel',
    save: 'Save',
    textSizeLabel: 'Text size',
    paragraph: 'Paragraph',
    heading1: 'Heading 1',
    heading2: 'Heading 2',
    heading3: 'Heading 3',
    bold: 'Bold',
    italic: 'Italic',
    underline: 'Underline',
    alignLeft: 'Align left',
    alignLeftTitle: 'Left',
    alignCenter: 'Center',
    alignRight: 'Align right',
    alignRightTitle: 'Right',
    alignJustify: 'Justify',
    bulletList: 'Bullet list',
    bulletListTitle: 'List',
    orderedList: 'Numbered list',
    orderedListTitle: 'Numbered',
    blockquote: 'Blockquote',
    horizontalRule: 'Horizontal rule',
    horizontalRuleTitle: 'Rule',
    undo: 'Undo',
    redo: 'Redo',
    noNotes: 'You have no saved notes',
    noteCount: (n: number) => `${n} ${n === 1 ? 'saved note' : 'saved notes'}`,
    colSection: 'Section',
    colLastUpdate: 'Last update',
    colCount: 'Count',
    colActions: 'Actions',
    collapse: 'Collapse',
    expand: 'Expand',
    collapseLabel: 'COLLAPSE',
    expandLabel: 'EXPAND',
    downloadTXT: 'Download TXT',
    preparingPDF: 'Preparing PDF...',
    exportPDF: 'Export PDF',
    emptyText: "You haven't created any notes yet",
    emptyHint: 'Select text on any page and click the notes icon to get started',
    noContent: 'No content',
    allPages: 'All pages',
    cover: 'Cover',
    page: (n: string) => `Page ${n}`
  }
};
