export const i18nNotes = {
  es: {
    title: 'Mis Notas',
    noNotes: 'No tienes notas guardadas',
    noteCount: (n: number) => `${n} ${n === 1 ? 'nota guardada' : 'notas guardadas'}`,
    colSection: 'Sección',
    colLastUpdate: 'Última actualización',
    colCount: 'Cantidad',
    colActions: 'Acciones',
    collapse: 'Contraer',
    expand: 'Expandir',
    collapseLabel: 'CONTRAER',
    expandLabel: 'EXPANDIR',
    downloadTXT: 'Descargar TXT',
    preparingPDF: 'Preparando PDF...',
    exportPDF: 'Exportar PDF',
    emptyText: 'Aún no has creado ninguna nota',
    emptyHint: 'Selecciona texto en cualquier página y haz clic en el ícono de notas para comenzar',
    noContent: 'Sin contenido',
    allPages: 'Todas las páginas',
    cover: 'Portada',
    page: (n: string) => `Página ${n}`
  },
  en: {
    title: 'My Notes',
    noNotes: 'You have no saved notes',
    noteCount: (n: number) => `${n} ${n === 1 ? 'saved note' : 'saved notes'}`,
    colSection: 'Section',
    colLastUpdate: 'Last update',
    colCount: 'Count',
    colActions: 'Actions',
    collapse: 'Collapse',
    expand: 'Expand',
    collapseLabel: 'COLLAPSE',
    expandLabel: 'EXPAND',
    downloadTXT: 'Download TXT',
    preparingPDF: 'Preparing PDF...',
    exportPDF: 'Export PDF',
    emptyText: "You haven't created any notes yet",
    emptyHint: 'Select text on any page and click the notes icon to get started',
    noContent: 'No content',
    allPages: 'All pages',
    cover: 'Cover',
    page: (n: string) => `Page ${n}`
  }
};
